# Basic
title: KK's Blog
subtitle: iNankai
description: Welcome~
# 头像里面的标题
avatarTitle: Sunshine
# 头像里面的描述
avatarDesc: 当代新青年^-^
url: "http://nkukk.github.io"


# Social
social:
    weibo: 5761346728 
    github: NKUkk
    mail: 775787333@qq.com

baidu:
   id:fd3fc97c29fb9a30377ccdeeebc024b8




permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# Navigation buttons in the front page.s
nav:
    - {title: 博客主页, description: archive, url: '/index'}
    - {title: 所有文章, description: archive, url: '/archive'}
   # - {title: 题库, description: questionbank, url: '/questionbank'}
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      

    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 5
paginate_path: "page/:num/"


